#!/bin/sh

find ./arch/x86  -type f -print | grep -E '\.(c(pp)?|h|S|ld.*)$' > cscope.files
find .  -path "./arch/*" -prune -o -type f -print | grep -E '\.(c(pp)?|h|S|ld.*)$' >> cscope.files
cscope -bkq -i cscope.files
ctags -R 
