set nocompatible
set nu
set ruler
set shiftwidth=4
set softtabstop=4
set tabstop=4
"set expandtab   "will not work when editting makefile
syntax on
filetype on
filetype plugin on
set incsearch
set hlsearch
if has("cscope")  
    set csprg=/usr/bin/cscope  
    set csto=0  
    set cst  
    set csverb  
    set cspc=3  
    "add any database in current dir  
    if filereadable("cscope.out")  
	    cs add cscope.out  
    "else search cscope.out elsewhere  
    else  
      let cscope_file=findfile("cscope.out", ".;")  
      let cscope_pre=matchstr(cscope_file, ".*/")  
      if !empty(cscope_file) && filereadable(cscope_file)  
	exe "cs add" cscope_file cscope_pre  
      endif        
    endif  
endif  
inoremap jj <Esc> 



