#!/bin/sh

declare -a sg_array

for i in $(seq 0 11)
do
	sg_array[$i]=$(sg_ses  /dev/sg17 -x $i | grep -i 'sas address' | grep -v attach | cut -d ':' -f 2)
done

for i in $(seq 0 11)
do
	echo ${sg_array[i]}
done

