#!/bin/sh
count=0
for i in $(seq 0 36)
do
	if [ -e "/sys/bus/scsi/devices/32:0:$i:0/" ]
	then
		echo -n "$i         " 
		cat "/sys/bus/scsi/devices/32:0:$i:0/sas_address"
		((count++))
	fi
done
echo "count is $((count-1))"
